# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-10-19 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0034_legendentryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastertile',
            name='id',
            field=models.TextField(null=True),
        ),
    ]
