# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-10-19 11:48
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Value as V
from django.db.models import CharField
from django.db.models.functions import Concat


def move_rid_forward(apps, schema_editor):
    """
    Copy srid from rasterlayers to metadata as a default value. This value will
    be overwritten automatically when parsing the layer.
    """
    RasterTile = apps.get_model("raster", "RasterTile")
    RasterTile.objects.all().update(
        id=Concat('rasterlayer_id', V('-'), 'tilez', V('-'), 'tilex', V('-'), 'tiley', output_field=CharField())
    )


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0035_rastertile_id'),
    ]

    operations = [
        migrations.RunPython(move_rid_forward),
    ]
