# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-10-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0036_auto_20161019_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastertile',
            name='rid',
        ),
        migrations.AlterField(
            model_name='rastertile',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
