# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-10-19 12:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0037_auto_20161019_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastertile',
            name='rasterlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster.RasterLayer'),
        ),
        migrations.AlterField(
            model_name='rastertile',
            name='tilex',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rastertile',
            name='tiley',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rastertile',
            name='tilez',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], db_index=True),
        ),
    ]
